#!/usr/bin/env bash
# Backup encryption for QrAi (P5.6). SOURCED by the backup/restore scripts, not executed directly.
#
# ─────────────────────────────────────────────────────────────────────────────────────────────────
# WHAT THIS PROTECTS
#
# The database dump holds learner accounts, consent records, and progress. The audio archive holds
# recordings of children reciting. Until this file, both were written to disk as plain compressed
# bytes: `pg_dump --format=custom` and `tar -czf` are COMPRESSION, and compression is not
# confidentiality. Anyone who could read the backup directory — or the off-host bucket the runbook
# tells operators to copy it to — could read everything in it.
#
# ─────────────────────────────────────────────────────────────────────────────────────────────────
# WHY PUBLIC-KEY ENVELOPE, AND NOT A PASSPHRASE
#
# This was first deferred on the grounds that "cipher choice plus key custody and rotation is an ADR
# the owner owns". That reasoning was right for SYMMETRIC encryption and wrong here, because it
# assumed the only option was a shared secret the backup host must hold.
#
# CMS envelope encryption (RFC 5652) needs only the recipient's PUBLIC certificate to encrypt. So:
#
#   • The backup host holds NO secret. It cannot decrypt its own backups. A compromise of the
#     backup machine — the realistic threat, since it is the box with every backup on it — yields
#     ciphertext and nothing else.
#   • The private key never appears in this repository, in any environment variable, in CI, or in
#     any process this tooling runs. It is generated by the owner, offline, once.
#   • There is no shared secret to rotate on staff changes, and no passphrase to leak through a
#     `ps` listing, a shell history, or a CI log.
#
# That removes key custody from the tooling's decisions entirely, which is why this could be
# implemented rather than deferred. Generating the keypair remains the owner's job and is documented
# in docs/BACKUP_RESTORE.md — this script will never create a key, and must never be changed to.
#
# ─────────────────────────────────────────────────────────────────────────────────────────────────
# CIPHER
#
# AES-256-GCM. Authenticated: a flipped byte anywhere in the ciphertext makes decryption FAIL rather
# than return plausible garbage, which for a backup is the difference between a loud failure and a
# corrupt restore nobody notices. Verified in scripts/backup-crypto.test.sh, both directions.
#
# ─────────────────────────────────────────────────────────────────────────────────────────────────
# FAILS CLOSED, WITH NO OPT-OUT
#
# No BACKUP_ALLOW_PLAINTEXT escape hatch exists, deliberately. An override flag is how a guard
# becomes decorative: it gets set once during an incident and stays set. If encryption cannot be
# performed, no backup is written and the script exits non-zero — a visible failure an operator
# fixes, instead of a plaintext archive of children's voices that reports success.
# ─────────────────────────────────────────────────────────────────────────────────────────────────

# Suffix appended to an otherwise-normal backup filename. Restore keys off this, so an operator who
# finds a bare `.dump` in a backup directory knows immediately it predates encryption.
BACKUP_CRYPTO_SUFFIX=".cms"

backup_crypto_require_openssl() {
  if ! command -v openssl >/dev/null 2>&1; then
    echo "error: openssl not found on PATH — backups cannot be encrypted, so none will be taken." >&2
    return 1
  fi
}

# Validate the recipient certificate BEFORE any expensive work starts. A pg_dump that runs for ten
# minutes and then fails to encrypt has both wasted the time and left the operator wondering whether
# a partial file on disk is sensitive.
backup_crypto_require_cert() {
  backup_crypto_require_openssl || return 1

  if [[ -z "${BACKUP_ENCRYPTION_CERT:-}" ]]; then
    cat >&2 <<'EOF'
error: BACKUP_ENCRYPTION_CERT is required and has NO default.

  This backup contains learner personal data and recordings of children. It is not written
  unencrypted, and there is no flag to make it so.

  BACKUP_ENCRYPTION_CERT must point at the PUBLIC certificate of the backup recipient. The matching
  PRIVATE key is generated by the owner, kept offline, and is never needed to take a backup — only
  to restore one.

  Create the keypair once (see docs/BACKUP_RESTORE.md § Backup encryption):

    openssl req -x509 -newkey rsa:4096 -days 3650 -sha256 -nodes \
      -keyout qrai-backup-private.key -out qrai-backup-public.crt \
      -subj "/CN=QrAi backup recipient"

  Then store qrai-backup-private.key OFFLINE (it is the only thing that can read your backups, and
  losing it means losing them), and point this variable at qrai-backup-public.crt.
EOF
    return 1
  fi

  if [[ ! -f "$BACKUP_ENCRYPTION_CERT" ]]; then
    echo "error: BACKUP_ENCRYPTION_CERT does not exist: $BACKUP_ENCRYPTION_CERT" >&2
    return 1
  fi

  if ! openssl x509 -in "$BACKUP_ENCRYPTION_CERT" -noout 2>/dev/null; then
    echo "error: BACKUP_ENCRYPTION_CERT is not a readable X.509 certificate: $BACKUP_ENCRYPTION_CERT" >&2
    echo "       Expected the PUBLIC .crt half of the keypair, not the private key." >&2
    return 1
  fi

  # A private key where the public cert belongs means the secret is on the backup host, which is the
  # exact property this design exists to avoid. Refuse it rather than encrypt successfully and let
  # the mistake persist unnoticed.
  if grep -q 'PRIVATE KEY' "$BACKUP_ENCRYPTION_CERT" 2>/dev/null; then
    echo "error: BACKUP_ENCRYPTION_CERT contains a PRIVATE KEY: $BACKUP_ENCRYPTION_CERT" >&2
    echo "       Only the public certificate belongs on a backup host. Split the file and keep the" >&2
    echo "       private half offline." >&2
    return 1
  fi
}

# Encrypt stdin -> "$1".
#
# Streaming is the point: the caller pipes `pg_dump`/`tar` straight in, so the plaintext never exists
# as a file. There is no window in which an unencrypted dump sits on disk waiting to be cleaned up,
# and no cleanup path that can be skipped by a crash or a SIGKILL.
backup_crypto_encrypt_stream() {
  local outfile="$1"
  umask 077
  openssl cms -encrypt -binary -aes-256-gcm -outform DER -out "$outfile" "$BACKUP_ENCRYPTION_CERT"
}

backup_crypto_is_encrypted() {
  [[ "$1" == *"$BACKUP_CRYPTO_SUFFIX" ]]
}

backup_crypto_require_key() {
  backup_crypto_require_openssl || return 1

  if [[ -z "${BACKUP_DECRYPTION_KEY:-}" ]]; then
    cat >&2 <<'EOF'
error: this backup is encrypted and BACKUP_DECRYPTION_KEY is not set.

  Point BACKUP_DECRYPTION_KEY at the PRIVATE key matching the certificate the backup was taken
  with. It is the only thing that can read this file; if it has been lost, this backup is
  unrecoverable and that is by design.

  This is the one step of a restore that requires retrieving the offline key, so it is also the step
  a disaster-recovery drill must actually rehearse — see docs/BACKUP_RESTORE.md.
EOF
    return 1
  fi

  if [[ ! -f "$BACKUP_DECRYPTION_KEY" ]]; then
    echo "error: BACKUP_DECRYPTION_KEY does not exist: $BACKUP_DECRYPTION_KEY" >&2
    return 1
  fi
}

# Decrypt "$1" -> "$2".
#
# Restoring needs a real file: `pg_restore` on a custom-format dump seeks, and `--jobs` requires it.
# So unlike the backup path, a restore DOES put plaintext on disk. The caller is responsible for
# creating "$2" under `mktemp` and removing it in a `trap`; `umask 077` here makes it owner-only for
# whatever window it exists in. This is a real difference between the two directions and is stated
# rather than hidden.
# Decrypt "$1" -> stdout.
#
# Preferred over backup_crypto_decrypt wherever the consumer can read a stream, because then the
# plaintext never lands on disk in either direction. `tar -xz` can; `pg_restore --jobs` cannot.
backup_crypto_decrypt_stream() {
  local infile="$1"
  if ! openssl cms -decrypt -binary -inform DER -in "$infile" -inkey "$BACKUP_DECRYPTION_KEY" 2>/dev/null; then
    echo "error: could not decrypt $infile — wrong key, or the file has been altered." >&2
    return 1
  fi
}

backup_crypto_decrypt() {
  local infile="$1" outfile="$2"
  umask 077
  if ! openssl cms -decrypt -binary -inform DER -in "$infile" -inkey "$BACKUP_DECRYPTION_KEY" -out "$outfile" 2>/dev/null; then
    echo "error: could not decrypt $infile" >&2
    echo "       Either BACKUP_DECRYPTION_KEY does not match the certificate this backup was taken" >&2
    echo "       with, or the file has been altered since it was written. AES-GCM is authenticated," >&2
    echo "       so a corrupted backup fails here rather than restoring silently damaged data." >&2
    return 1
  fi
}
