/**
 * Licensed ayah translations (e.g. Central Kurdish / Sorani). Generated by
 * scripts/fetch-translations.mjs from api.quran.com v4 and stored as static JSON under
 * src/data/translations/<slug>/. Text is stored VERBATIM (QuranEnc license: no modification);
 * ayahs the source has no translation for are recorded in `missingAyahs`, never invented. See
 * docs/DATA_LICENSES.md#ckb-sorani-translation.
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadSurahJson } from "./load-surah-json";

const DIR = join(dirname(fileURLToPath(import.meta.url)), "data", "translations");

export interface AyahTranslation {
  ayah: number;
  text: string;
}

export interface MissingTranslation {
  ayah: number;
  reason: string;
}

export interface SurahTranslation {
  surah: number;
  slug: string;
  translationId: number;
  translator: string;
  language: string;
  source: string;
  publisher: string;
  license: string;
  fetchedAt: string;
  ayahs: AyahTranslation[];
  missingAyahs: MissingTranslation[];
}

/** Load a surah's translation for a slug, or null when none was ingested. Node-only loader. */
export function getSurahTranslation(surahNumber: number, slug = "ckb-burhan-muhammad"): SurahTranslation | null {
  return loadSurahJson<SurahTranslation>(DIR, slug, surahNumber);
}
