/**
 * Licensed ayah translations (e.g. Central Kurdish / Sorani). Generated by
 * scripts/fetch-translations.mjs from api.quran.com v4 and stored as static JSON under
 * src/data/translations/<slug>/. Text is stored VERBATIM (QuranEnc license: no modification);
 * ayahs the source has no translation for are recorded in `missingAyahs`, never invented. See
 * docs/DATA_LICENSES.md#ckb-sorani-translation.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIR = join(__dirname, "data", "translations");

export interface AyahTranslation {
  ayah: number;
  text: string;
}

export interface MissingTranslation {
  ayah: number;
  reason: string;
}

export interface SurahTranslation {
  surah: number;
  slug: string;
  translationId: number;
  translator: string;
  language: string;
  source: string;
  publisher: string;
  license: string;
  fetchedAt: string;
  ayahs: AyahTranslation[];
  missingAyahs: MissingTranslation[];
}

const cache = new Map<string, SurahTranslation | null>();

/** Load a surah's translation for a slug, or null when none was ingested. Node-only loader. */
export function getSurahTranslation(surahNumber: number, slug = "ckb-burhan-muhammad"): SurahTranslation | null {
  if (surahNumber < 1 || surahNumber > 114) {
    throw new Error(`Invalid surah number: ${surahNumber}. Must be 1-114.`);
  }
  const key = `${slug}/${surahNumber}`;
  if (cache.has(key)) return cache.get(key) ?? null;
  const file = join(DIR, slug, `surah-${String(surahNumber).padStart(3, "0")}.json`);
  let data: SurahTranslation | null = null;
  try {
    data = JSON.parse(readFileSync(file, "utf8")) as SurahTranslation;
  } catch {
    data = null;
  }
  cache.set(key, data);
  return data;
}
