/**
 * Word-level audio-segment timings for reference recitations.
 *
 * Data is generated by scripts/fetch-word-timings.mjs from api.quran.com v4 and stored as static
 * JSON under src/data/word-timings/<reciter>/. Every timing is mapped to a canonical word id
 * (`surah:ayah:index`) and verified against the canonical text; words with no matched segment
 * (basmala prefixes, standalone waqf marks) simply carry no timing. See
 * docs/DATA_LICENSES.md#quran-com-word-segments-audio for licensing/attribution.
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadSurahJson } from "./load-surah-json";

const TIMINGS_DIR = join(dirname(fileURLToPath(import.meta.url)), "data", "word-timings");

export interface WordTiming {
  /** Canonical word id, `surah:ayah:index` (1-based index into the full canonical word list). */
  wordId: string;
  startMs: number;
  endMs: number;
}

export interface AyahTimings {
  ayah: number;
  /** Path relative to the surah's `audioBase`, e.g. `Alafasy/mp3/001001.mp3`. */
  audioUrl: string;
  words: WordTiming[];
}

export interface ExcludedAyah {
  ayah: number;
  /** Why this ayah has no timings — an honest audit trail, never a silent omission. */
  reason: string;
}

export interface SurahTimings {
  surah: number;
  reciter: string;
  reciterName: string;
  source: string;
  /** Absolute base for every ayah `audioUrl` (Quran.com's master, matched to the segments). */
  audioBase: string;
  license: string;
  ayahs: AyahTimings[];
  excludedAyahs: ExcludedAyah[];
}

/**
 * Load word timings for a surah, or null when no timing data has been ingested for it yet.
 * Node-only (reads the packaged JSON); the web app consumes the JSON via a bundler import.
 */
export function getWordTimings(surahNumber: number, reciter = "alafasy"): SurahTimings | null {
  return loadSurahJson<SurahTimings>(TIMINGS_DIR, reciter, surahNumber);
}
