-- 0007_seed_surah_names.sql
-- Canonical surah metadata (114 surahs) from the full-quran import data
-- (alquran.cloud / quran-uthmani). Real reference data — surah names never change.
-- Fixes list_surahs returning synthetic 'Surah N' placeholders.

create table if not exists canonical_surahs (
  surah_number integer primary key,
  name_arabic text not null,
  english_name text not null,
  english_translation text not null,
  revelation_type text not null,
  ayah_count integer not null
);

insert into canonical_surahs (surah_number, name_arabic, english_name, english_translation, revelation_type, ayah_count) values
  (1, 'سُورَةُ ٱلْفَاتِحَةِ', 'Al-Faatiha', 'The Opening', 'Meccan', 7),
  (2, 'سُورَةُ البَقَرَةِ', 'Al-Baqara', 'The Cow', 'Medinan', 286),
  (3, 'سُورَةُ آلِ عِمۡرَانَ', 'Aal-i-Imraan', 'The Family of Imraan', 'Medinan', 200),
  (4, 'سُورَةُ النِّسَاءِ', 'An-Nisaa', 'The Women', 'Medinan', 176),
  (5, 'سُورَةُ المَائـِدَةِ', 'Al-Maaida', 'The Table', 'Medinan', 120),
  (6, 'سُورَةُ الأَنۡعَامِ', 'Al-An''aam', 'The Cattle', 'Meccan', 165),
  (7, 'سُورَةُ الأَعۡرَافِ', 'Al-A''raaf', 'The Heights', 'Meccan', 206),
  (8, 'سُورَةُ الأَنفَالِ', 'Al-Anfaal', 'The Spoils of War', 'Medinan', 75),
  (9, 'سُورَةُ التَّوۡبَةِ', 'At-Tawba', 'The Repentance', 'Medinan', 129),
  (10, 'سُورَةُ يُونُسَ', 'Yunus', 'Jonas', 'Meccan', 109),
  (11, 'سُورَةُ هُودٍ', 'Hud', 'Hud', 'Meccan', 123),
  (12, 'سُورَةُ يُوسُفَ', 'Yusuf', 'Joseph', 'Meccan', 111),
  (13, 'سُورَةُ الرَّعۡدِ', 'Ar-Ra''d', 'The Thunder', 'Medinan', 43),
  (14, 'سُورَةُ إِبۡرَاهِيمَ', 'Ibrahim', 'Abraham', 'Meccan', 52),
  (15, 'سُورَةُ الحِجۡرِ', 'Al-Hijr', 'The Rock', 'Meccan', 99),
  (16, 'سُورَةُ النَّحۡلِ', 'An-Nahl', 'The Bee', 'Meccan', 128),
  (17, 'سُورَةُ الإِسۡرَاءِ', 'Al-Israa', 'The Night Journey', 'Meccan', 111),
  (18, 'سُورَةُ الكَهۡفِ', 'Al-Kahf', 'The Cave', 'Meccan', 110),
  (19, 'سُورَةُ مَرۡيَمَ', 'Maryam', 'Mary', 'Meccan', 98),
  (20, 'سُورَةُ طه', 'Taa-Haa', 'Taa-Haa', 'Meccan', 135),
  (21, 'سُورَةُ الأَنبِيَاءِ', 'Al-Anbiyaa', 'The Prophets', 'Meccan', 112),
  (22, 'سُورَةُ الحَجِّ', 'Al-Hajj', 'The Pilgrimage', 'Medinan', 78),
  (23, 'سُورَةُ المُؤۡمِنُونَ', 'Al-Muminoon', 'The Believers', 'Meccan', 118),
  (24, 'سُورَةُ النُّورِ', 'An-Noor', 'The Light', 'Medinan', 64),
  (25, 'سُورَةُ الفُرۡقَانِ', 'Al-Furqaan', 'The Criterion', 'Meccan', 77),
  (26, 'سُورَةُ الشُّعَرَاءِ', 'Ash-Shu''araa', 'The Poets', 'Meccan', 227),
  (27, 'سُورَةُ النَّمۡلِ', 'An-Naml', 'The Ant', 'Meccan', 93),
  (28, 'سُورَةُ القَصَصِ', 'Al-Qasas', 'The Stories', 'Meccan', 88),
  (29, 'سُورَةُ العَنكَبُوتِ', 'Al-Ankaboot', 'The Spider', 'Meccan', 69),
  (30, 'سُورَةُ الرُّومِ', 'Ar-Room', 'The Romans', 'Meccan', 60),
  (31, 'سُورَةُ لُقۡمَانَ', 'Luqman', 'Luqman', 'Meccan', 34),
  (32, 'سُورَةُ السَّجۡدَةِ', 'As-Sajda', 'The Prostration', 'Meccan', 30),
  (33, 'سُورَةُ الأَحۡزَابِ', 'Al-Ahzaab', 'The Clans', 'Medinan', 73),
  (34, 'سُورَةُ سَبَإٍ', 'Saba', 'Sheba', 'Meccan', 54),
  (35, 'سُورَةُ فَاطِرٍ', 'Faatir', 'The Originator', 'Meccan', 45),
  (36, 'سُورَةُ يسٓ', 'Yaseen', 'Yaseen', 'Meccan', 83),
  (37, 'سُورَةُ الصَّافَّاتِ', 'As-Saaffaat', 'Those drawn up in Ranks', 'Meccan', 182),
  (38, 'سُورَةُ صٓ', 'Saad', 'The letter Saad', 'Meccan', 88),
  (39, 'سُورَةُ الزُّمَرِ', 'Az-Zumar', 'The Groups', 'Meccan', 75),
  (40, 'سُورَةُ غَافِرٍ', 'Ghafir', 'The Forgiver', 'Meccan', 85),
  (41, 'سُورَةُ فُصِّلَتۡ', 'Fussilat', 'Explained in detail', 'Meccan', 54),
  (42, 'سُورَةُ الشُّورَىٰ', 'Ash-Shura', 'Consultation', 'Meccan', 53),
  (43, 'سُورَةُ الزُّخۡرُفِ', 'Az-Zukhruf', 'Ornaments of gold', 'Meccan', 89),
  (44, 'سُورَةُ الدُّخَانِ', 'Ad-Dukhaan', 'The Smoke', 'Meccan', 59),
  (45, 'سُورَةُ الجَاثِيَةِ', 'Al-Jaathiya', 'Crouching', 'Meccan', 37),
  (46, 'سُورَةُ الأَحۡقَافِ', 'Al-Ahqaf', 'The Dunes', 'Meccan', 35),
  (47, 'سُورَةُ مُحَمَّدٍ', 'Muhammad', 'Muhammad', 'Medinan', 38),
  (48, 'سُورَةُ الفَتۡحِ', 'Al-Fath', 'The Victory', 'Medinan', 29),
  (49, 'سُورَةُ الحُجُرَاتِ', 'Al-Hujuraat', 'The Inner Apartments', 'Medinan', 18),
  (50, 'سُورَةُ قٓ', 'Qaaf', 'The letter Qaaf', 'Meccan', 45),
  (51, 'سُورَةُ الذَّارِيَاتِ', 'Adh-Dhaariyat', 'The Winnowing Winds', 'Meccan', 60),
  (52, 'سُورَةُ الطُّورِ', 'At-Tur', 'The Mount', 'Meccan', 49),
  (53, 'سُورَةُ النَّجۡمِ', 'An-Najm', 'The Star', 'Meccan', 62),
  (54, 'سُورَةُ القَمَرِ', 'Al-Qamar', 'The Moon', 'Meccan', 55),
  (55, 'سُورَةُ الرَّحۡمَٰن', 'Ar-Rahmaan', 'The Beneficent', 'Medinan', 78),
  (56, 'سُورَةُ الوَاقِعَةِ', 'Al-Waaqia', 'The Inevitable', 'Meccan', 96),
  (57, 'سُورَةُ الحَدِيدِ', 'Al-Hadid', 'The Iron', 'Medinan', 29),
  (58, 'سُورَةُ المُجَادلَةِ', 'Al-Mujaadila', 'The Pleading Woman', 'Medinan', 22),
  (59, 'سُورَةُ الحَشۡرِ', 'Al-Hashr', 'The Exile', 'Medinan', 24),
  (60, 'سُورَةُ المُمۡتَحنَةِ', 'Al-Mumtahana', 'She that is to be examined', 'Medinan', 13),
  (61, 'سُورَةُ الصَّفِّ', 'As-Saff', 'The Ranks', 'Medinan', 14),
  (62, 'سُورَةُ الجُمُعَةِ', 'Al-Jumu''a', 'Friday', 'Medinan', 11),
  (63, 'سُورَةُ المُنَافِقُونَ', 'Al-Munaafiqoon', 'The Hypocrites', 'Medinan', 11),
  (64, 'سُورَةُ التَّغَابُنِ', 'At-Taghaabun', 'Mutual Disillusion', 'Medinan', 18),
  (65, 'سُورَةُ الطَّلَاقِ', 'At-Talaaq', 'Divorce', 'Medinan', 12),
  (66, 'سُورَةُ التَّحۡرِيمِ', 'At-Tahrim', 'The Prohibition', 'Medinan', 12),
  (67, 'سُورَةُ المُلۡكِ', 'Al-Mulk', 'The Sovereignty', 'Meccan', 30),
  (68, 'سُورَةُ القَلَمِ', 'Al-Qalam', 'The Pen', 'Meccan', 52),
  (69, 'سُورَةُ الحَاقَّةِ', 'Al-Haaqqa', 'The Reality', 'Meccan', 52),
  (70, 'سُورَةُ المَعَارِجِ', 'Al-Ma''aarij', 'The Ascending Stairways', 'Meccan', 44),
  (71, 'سُورَةُ نُوحٍ', 'Nooh', 'Noah', 'Meccan', 28),
  (72, 'سُورَةُ الجِنِّ', 'Al-Jinn', 'The Jinn', 'Meccan', 28),
  (73, 'سُورَةُ المُزَّمِّلِ', 'Al-Muzzammil', 'The Enshrouded One', 'Meccan', 20),
  (74, 'سُورَةُ المُدَّثِّرِ', 'Al-Muddaththir', 'The Cloaked One', 'Meccan', 56),
  (75, 'سُورَةُ القِيَامَةِ', 'Al-Qiyaama', 'The Resurrection', 'Meccan', 40),
  (76, 'سُورَةُ الإِنسَانِ', 'Al-Insaan', 'Man', 'Medinan', 31),
  (77, 'سُورَةُ المُرۡسَلَاتِ', 'Al-Mursalaat', 'The Emissaries', 'Meccan', 50),
  (78, 'سُورَةُ النَّبَإِ', 'An-Naba', 'The Announcement', 'Meccan', 40),
  (79, 'سُورَةُ النَّازِعَاتِ', 'An-Naazi''aat', 'Those who drag forth', 'Meccan', 46),
  (80, 'سُورَةُ عَبَسَ', 'Abasa', 'He frowned', 'Meccan', 42),
  (81, 'سُورَةُ التَّكۡوِيرِ', 'At-Takwir', 'The Overthrowing', 'Meccan', 29),
  (82, 'سُورَةُ الانفِطَارِ', 'Al-Infitaar', 'The Cleaving', 'Meccan', 19),
  (83, 'سُورَةُ المُطَفِّفِينَ', 'Al-Mutaffifin', 'Defrauding', 'Meccan', 36),
  (84, 'سُورَةُ الانشِقَاقِ', 'Al-Inshiqaaq', 'The Splitting Open', 'Meccan', 25),
  (85, 'سُورَةُ البُرُوجِ', 'Al-Burooj', 'The Constellations', 'Meccan', 22),
  (86, 'سُورَةُ الطَّارِقِ', 'At-Taariq', 'The Morning Star', 'Meccan', 17),
  (87, 'سُورَةُ الأَعۡلَىٰ', 'Al-A''laa', 'The Most High', 'Meccan', 19),
  (88, 'سُورَةُ الغَاشِيَةِ', 'Al-Ghaashiya', 'The Overwhelming', 'Meccan', 26),
  (89, 'سُورَةُ الفَجۡرِ', 'Al-Fajr', 'The Dawn', 'Meccan', 30),
  (90, 'سُورَةُ البَلَدِ', 'Al-Balad', 'The City', 'Meccan', 20),
  (91, 'سُورَةُ الشَّمۡسِ', 'Ash-Shams', 'The Sun', 'Meccan', 15),
  (92, 'سُورَةُ اللَّيۡلِ', 'Al-Lail', 'The Night', 'Meccan', 21),
  (93, 'سُورَةُ الضُّحَىٰ', 'Ad-Dhuhaa', 'The Morning Hours', 'Meccan', 11),
  (94, 'سُورَةُ الشَّرۡحِ', 'Ash-Sharh', 'The Consolation', 'Meccan', 8),
  (95, 'سُورَةُ التِّينِ', 'At-Tin', 'The Fig', 'Meccan', 8),
  (96, 'سُورَةُ العَلَقِ', 'Al-Alaq', 'The Clot', 'Meccan', 19),
  (97, 'سُورَةُ القَدۡرِ', 'Al-Qadr', 'The Power, Fate', 'Meccan', 5),
  (98, 'سُورَةُ البَيِّنَةِ', 'Al-Bayyina', 'The Evidence', 'Medinan', 8),
  (99, 'سُورَةُ الزَّلۡزَلَةِ', 'Az-Zalzala', 'The Earthquake', 'Medinan', 8),
  (100, 'سُورَةُ العَادِيَاتِ', 'Al-Aadiyaat', 'The Chargers', 'Meccan', 11),
  (101, 'سُورَةُ القَارِعَةِ', 'Al-Qaari''a', 'The Calamity', 'Meccan', 11),
  (102, 'سُورَةُ التَّكَاثُرِ', 'At-Takaathur', 'Competition', 'Meccan', 8),
  (103, 'سُورَةُ العَصۡرِ', 'Al-Asr', 'The Declining Day, Epoch', 'Meccan', 3),
  (104, 'سُورَةُ الهُمَزَةِ', 'Al-Humaza', 'The Traducer', 'Meccan', 9),
  (105, 'سُورَةُ الفِيلِ', 'Al-Fil', 'The Elephant', 'Meccan', 5),
  (106, 'سُورَةُ قُرَيۡشٍ', 'Quraish', 'Quraysh', 'Meccan', 4),
  (107, 'سُورَةُ المَاعُونِ', 'Al-Maa''un', 'Almsgiving', 'Meccan', 7),
  (108, 'سُورَةُ الكَوۡثَرِ', 'Al-Kawthar', 'Abundance', 'Meccan', 3),
  (109, 'سُورَةُ الكَافِرُونَ', 'Al-Kaafiroon', 'The Disbelievers', 'Meccan', 6),
  (110, 'سُورَةُ النَّصۡرِ', 'An-Nasr', 'Divine Support', 'Medinan', 3),
  (111, 'سُورَةُ المَسَدِ', 'Al-Masad', 'The Palm Fibre', 'Meccan', 5),
  (112, 'سُورَةُ الإِخۡلَاصِ', 'Al-Ikhlaas', 'Sincerity', 'Meccan', 4),
  (113, 'سُورَةُ الفَلَقِ', 'Al-Falaq', 'The Dawn', 'Meccan', 5),
  (114, 'سُورَةُ النَّاسِ', 'An-Naas', 'Mankind', 'Meccan', 6)
on conflict (surah_number) do update set
  name_arabic = excluded.name_arabic,
  english_name = excluded.english_name,
  english_translation = excluded.english_translation,
  revelation_type = excluded.revelation_type,
  ayah_count = excluded.ayah_count;
