#!/usr/bin/env bash
set -euo pipefail

# Seed the Postgres database with the full Quran text.
#
# SQL is generated by scripts/write-full-quran-sql-seed.mjs (via jiti, imports
# @quran-ai/quran-data's TS source directly — see package.json's "seed:full-quran:sql"), which
# uses buildFullQuranSurahBundle + toCanonicalSqlSeed: the SAME checksum functions
# (createCanonicalChecksum/createCanonicalAyahChecksum) that @quran-ai/contracts's
# verifyCanonicalWord/verifyCanonicalAyah validate against. A prior version of this script computed
# source_checksum inline as fnv1a32(rawText) — a format verifyCanonicalWord/verifyCanonicalAyah could
# never validate (see docs/DECISIONS.md). The generated INSERTs use ON CONFLICT (id) DO UPDATE, so
# re-running this script against an already-seeded database (e.g. one seeded before this fix) corrects
# every row's checksum in place.

PSQL="${PSQL:-/opt/homebrew/opt/postgresql@16/bin/psql}"
DB_HOST="${DB_HOST:-localhost}"
DB_USER="${DB_USER:-hawzhin}"
DB_NAME="${DB_NAME:-quran_ai}"
PACKAGE_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [[ -n "${DATABASE_URL:-}" ]]; then
  # A release smoke run supplies an isolated database as one connection URL.
  # Keep it opaque in logs: URLs may contain credentials.
  DB_ARGS=(--dbname "$DATABASE_URL")
  DATABASE_LABEL="DATABASE_URL (redacted)"
else
  DB_ARGS=(-h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME")
  DATABASE_LABEL="$DB_HOST/$DB_NAME"
fi

echo "=== Seeding full Quran to Postgres ==="
echo "Database: $DATABASE_LABEL"
echo ""

# Create seed institution and users
$PSQL "${DB_ARGS[@]}" <<'SQL'
INSERT INTO institutions (id, name, region) VALUES
  ('hikmah-pilot-erbil', 'Hikmah Quran Academy', 'Erbil, Kurdistan')
ON CONFLICT (id) DO NOTHING;

INSERT INTO model_versions (id, kind, version, status) VALUES
  ('model-v0.3', 'alignment', '0.3', 'eval-passed'),
  ('tajweed-v0.1', 'tajweed', '0.1', 'eval-passed'),
  ('agent-v0.1', 'agent', '0.1', 'draft'),
  ('planner-v0.1', 'planner', '0.1', 'draft')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, tenant_id, display_name, role, language) VALUES
  ('teacher-1', 'hikmah-pilot-erbil', 'Ustadh Barzan', 'teacher', 'ar'),
  ('admin-1', 'hikmah-pilot-erbil', 'Admin', 'admin', 'en'),
  ('learner-1', 'hikmah-pilot-erbil', 'Soran Othman', 'learner', 'ckb')
ON CONFLICT (id) DO NOTHING;
SQL

echo "Seed institution, model versions, and users created."
echo ""

# Generate SQL from the full Quran data (via @quran-ai/quran-data's checksum-correct builder) and
# pipe to psql. The trailing `|| true` this used to end with swallowed EVERY failure in the whole
# pipeline, not just grep's benign "no non-INSERT lines to show" exit (1) -- verified empirically:
# `set -euo pipefail; (exit N) | cat | grep -v nomatch || true` always continues with exit 0, no
# matter what N is. That meant a crash in write-full-quran-sql-seed.mjs OR a rejected/malformed
# INSERT from psql would leave this script silently continuing to "Verifying counts" as if nothing
# had gone wrong, instead of halting with a clear error -- exactly the "swallowed failure that
# should propagate" class of bug already fixed once this session in scripts/load-test.js. Wrapping
# in `if ... ; then :; fi` avoids `set -e` aborting on the pipeline's exit status (needed because
# `pipefail` makes grep's benign exit 1 propagate) while still capturing each stage's REAL exit
# code via PIPESTATUS, read immediately afterward before any other command can overwrite it.
# Copy the WHOLE array in one atomic assignment before reading individual indices -- verified
# empirically that under `set -u`, reading PIPESTATUS[0] then PIPESTATUS[1] as separate statements
# throws "unbound variable" on the second read (a real bash quirk, not a typo): the act of reading
# one index appears to disturb the array's state before the next read.
if (cd "$PACKAGE_DIR" && pnpm exec jiti scripts/write-full-quran-sql-seed.mjs) \
  | $PSQL "${DB_ARGS[@]}" -q 2>&1 | grep -v "^INSERT"; then
  :
fi
PIPE_STATUS=("${PIPESTATUS[@]}")
SEED_EXIT="${PIPE_STATUS[0]}"
PSQL_EXIT="${PIPE_STATUS[1]}"
if [ "$SEED_EXIT" -ne 0 ] || [ "$PSQL_EXIT" -ne 0 ]; then
  echo "ERROR: full-Quran seed failed (write-full-quran-sql-seed.mjs exit=$SEED_EXIT, psql exit=$PSQL_EXIT)" >&2
  exit 1
fi

echo ""
echo "=== Verifying counts ==="
# CANONICAL_AYAH_COUNTS (packages/quran-data/src/canonical-ayah-counts.ts) sums to exactly 6236 --
# independent ground truth from the established recitation tradition. Previously this step only
# printed the counts for a human to eyeball; now it actually fails the script if seeding produced
# the wrong number of ayahs or surahs, the same "don't trust the caller" pattern already applied to
# validateCanonicalImportBundle in packages/quran-data/src/index.ts.
COUNTS="$($PSQL "${DB_ARGS[@]}" -t -A -F' ' -c "SELECT (SELECT count(*) FROM canonical_ayahs), (SELECT count(DISTINCT surah_number) FROM canonical_ayahs), (SELECT count(*) FROM canonical_words);")"
AYAH_COUNT="$(echo "$COUNTS" | cut -d' ' -f1)"
SURAH_COUNT="$(echo "$COUNTS" | cut -d' ' -f2)"
WORD_COUNT="$(echo "$COUNTS" | cut -d' ' -f3)"
echo "ayah_count: $AYAH_COUNT"
echo "surah_count: $SURAH_COUNT"
echo "word_count: $WORD_COUNT"
if [ "$AYAH_COUNT" -ne 6236 ] || [ "$SURAH_COUNT" -ne 114 ] || [ "$WORD_COUNT" -eq 0 ]; then
  echo "ERROR: seeded counts do not match the canonical Quran (expected 6236 ayahs across 114 surahs, got $AYAH_COUNT ayahs across $SURAH_COUNT surahs, $WORD_COUNT words)." >&2
  exit 1
fi
echo "Counts verified against the canonical 6236-ayah, 114-surah reference."
