#!/usr/bin/env bash
set -euo pipefail

# Seed the Postgres database with the full Quran text.
#
# SQL is generated by scripts/write-full-quran-sql-seed.mjs (via jiti, imports
# @quran-ai/quran-data's TS source directly — see package.json's "seed:full-quran:sql"), which
# uses buildFullQuranSurahBundle + toCanonicalSqlSeed: the SAME checksum functions
# (createCanonicalChecksum/createCanonicalAyahChecksum) that @quran-ai/contracts's
# verifyCanonicalWord/verifyCanonicalAyah validate against. A prior version of this script computed
# source_checksum inline as fnv1a32(rawText) — a format verifyCanonicalWord/verifyCanonicalAyah could
# never validate (see docs/DECISIONS.md). The generated INSERTs use ON CONFLICT (id) DO UPDATE, so
# re-running this script against an already-seeded database (e.g. one seeded before this fix) corrects
# every row's checksum in place.

PSQL="${PSQL:-/opt/homebrew/opt/postgresql@16/bin/psql}"
DB_HOST="${DB_HOST:-localhost}"
DB_USER="${DB_USER:-hawzhin}"
DB_NAME="${DB_NAME:-quran_ai}"
PACKAGE_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== Seeding full Quran to Postgres ==="
echo "Database: $DB_HOST/$DB_NAME"
echo ""

# Create seed institution and users
$PSQL -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" <<'SQL'
INSERT INTO institutions (id, name, region) VALUES
  ('hikmah-pilot-erbil', 'Hikmah Quran Academy', 'Erbil, Kurdistan')
ON CONFLICT (id) DO NOTHING;

INSERT INTO model_versions (id, kind, version, status) VALUES
  ('model-v0.3', 'alignment', '0.3', 'eval-passed'),
  ('tajweed-v0.1', 'tajweed', '0.1', 'eval-passed'),
  ('agent-v0.1', 'agent', '0.1', 'draft'),
  ('planner-v0.1', 'planner', '0.1', 'draft')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, tenant_id, display_name, role, language) VALUES
  ('teacher-1', 'hikmah-pilot-erbil', 'Ustadh Barzan', 'teacher', 'ar'),
  ('admin-1', 'hikmah-pilot-erbil', 'Admin', 'admin', 'en'),
  ('learner-1', 'hikmah-pilot-erbil', 'Soran Othman', 'learner', 'ckb')
ON CONFLICT (id) DO NOTHING;
SQL

echo "Seed institution, model versions, and users created."
echo ""

# Generate SQL from the full Quran data (via @quran-ai/quran-data's checksum-correct builder) and
# pipe to psql.
(cd "$PACKAGE_DIR" && pnpm exec jiti scripts/write-full-quran-sql-seed.mjs) \
  | $PSQL -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -q 2>&1 | grep -v "^INSERT" || true

echo ""
echo "=== Verifying counts ==="
$PSQL -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c "SELECT count(*) as ayah_count FROM canonical_ayahs;" -c "SELECT count(*) as word_count FROM canonical_words;" -c "SELECT count(*) as surah_count FROM (SELECT DISTINCT surah_number FROM canonical_ayahs) s;"
